name = "kryptos"
version = "0.0.1"
description = "Cryptography library for Gleam targeting Erlang and JavaScript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "kryptos" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.5.3 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"

[javascript]
runtime = "node"
