name = "kryptos"
version = "0.0.1"
description = "Cryptography library for Gleam targeting Erlang and JavaScript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "kryptos" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "bun"
