name = "kryptos"
version = "1.3.0"
description = "Cryptography library for Gleam targeting Erlang and JavaScript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "kryptos" }

[dependencies]
bigi = ">= 4.1.0 and < 5.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
birdie = ">= 1.5.3 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
qcheck = ">= 1.0.3 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
unitest = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "node"
